# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/qt_ui_simple.ui'
#
# Created by: PyQt5 UI code generator 5.8.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1032, 764)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(8)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(-1, -1, -1, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.options = QtWidgets.QGridLayout()
        self.options.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.options.setContentsMargins(1, 5, 5, 5)
        self.options.setObjectName("options")
        self.getAllPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.getAllPushButton.setObjectName("getAllPushButton")
        self.options.addWidget(self.getAllPushButton, 0, 1, 1, 1)
        self.getCurrentPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.getCurrentPushButton.setObjectName("getCurrentPushButton")
        self.options.addWidget(self.getCurrentPushButton, 0, 0, 1, 1)
        self.sendCurrentPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendCurrentPushButton.setObjectName("sendCurrentPushButton")
        self.options.addWidget(self.sendCurrentPushButton, 1, 0, 1, 1)
        self.sendAllPushButton = QtWidgets.QPushButton(self.centralwidget)
        self.sendAllPushButton.setObjectName("sendAllPushButton")
        self.options.addWidget(self.sendAllPushButton, 1, 1, 1, 1)
        self.liveUpdateCheckBox = QtWidgets.QCheckBox(self.centralwidget)
        self.liveUpdateCheckBox.setObjectName("liveUpdateCheckBox")
        self.options.addWidget(self.liveUpdateCheckBox, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.options, 1, 0, 1, 1)
        self.programmes = QtWidgets.QTabWidget(self.centralwidget)
        self.programmes.setEnabled(True)
        self.programmes.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.programmes.setObjectName("programmes")
        # Programmes
        self.progs = []
        for prog_i in range(1, 5):
            prog = {}
            prog["prog1"] = QtWidgets.QWidget()
            prog["prog1"].setObjectName("prog%s" % prog_i)
            self.gridLayout_2 = QtWidgets.QGridLayout(prog["prog1"])
            self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
            self.gridLayout_2.setObjectName("gridLayout_2")
            self.knobsGroupBox = QtWidgets.QGroupBox(prog["prog1"])
            self.knobsGroupBox.setObjectName("knobsGroupBox")
            self.gridLayout_5 = QtWidgets.QGridLayout(self.knobsGroupBox)
            self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
            self.gridLayout_5.setSpacing(0)
            self.gridLayout_5.setObjectName("gridLayout_5")

            # Knobs
            prog["knobs"] = []
            for knob_i in range(8):
                knob = {}
                knob["knobGroupBox"] = QtWidgets.QGroupBox(self.knobsGroupBox)
                knob["knobGroupBox"].setObjectName("knobGroupBox")
                knob["knobGridLayout"] = QtWidgets.QGridLayout(knob["knobGroupBox"])
                knob["knobGridLayout"].setContentsMargins(0, 0, 0, 0)
                knob["knobGridLayout"].setSpacing(0)
                knob["knobGridLayout"].setObjectName("knobGridLayout")
                knob["knobMinSpinBox"] = QtWidgets.QSpinBox(knob["knobGroupBox"])
                knob["knobMinSpinBox"].setMaximum(127)
                knob["knobMinSpinBox"].setObjectName("knobMinSpinBox")
                knob["knobGridLayout"].addWidget(knob["knobMinSpinBox"], 1, 1, 1, 1)
                knob["knobCCSpinBox"] = QtWidgets.QSpinBox(knob["knobGroupBox"])
                knob["knobCCSpinBox"].setMaximum(127)
                knob["knobCCSpinBox"].setObjectName("knobCCSpinBox")
                knob["knobGridLayout"].addWidget(knob["knobCCSpinBox"], 0, 1, 1, 1)
                knob["knobMinLabel"] = QtWidgets.QLabel(knob["knobGroupBox"])
                knob["knobMinLabel"].setObjectName("knobMinLabel")
                knob["knobGridLayout"].addWidget(knob["knobMinLabel"], 1, 0, 1, 1)
                knob["knobMaxSpinBox"] = QtWidgets.QSpinBox(knob["knobGroupBox"])
                knob["knobMaxSpinBox"].setMaximum(127)
                knob["knobMaxSpinBox"].setProperty("value", 127)
                knob["knobMaxSpinBox"].setObjectName("knobMaxSpinBox")
                knob["knobGridLayout"].addWidget(knob["knobMaxSpinBox"], 2, 1, 1, 1)
                knob["knobMaxLabel"] = QtWidgets.QLabel(knob["knobGroupBox"])
                knob["knobMaxLabel"].setObjectName("knobMaxLabel")
                knob["knobGridLayout"].addWidget(knob["knobMaxLabel"], 2, 0, 1, 1)
                knob["knobCCLabel"] = QtWidgets.QLabel(knob["knobGroupBox"])
                knob["knobCCLabel"].setObjectName("knobCCLabel")
                knob["knobGridLayout"].addWidget(knob["knobCCLabel"], 0, 0, 1, 1)
                self.gridLayout_5.addWidget(knob["knobGroupBox"], knob_i/4+1, knob_i%4, 1, 1)
                prog["knobs"].append(knob)
            self.gridLayout_2.addWidget(self.knobsGroupBox, 0, 1, 1, 1)

            self.miscLayout = QtWidgets.QHBoxLayout()
            self.miscLayout.setObjectName("miscLayout")
            self.joystickLayout = QtWidgets.QGroupBox(prog["prog1"])
            self.joystickLayout.setObjectName("joystickLayout")
            self.verticalLayout = QtWidgets.QVBoxLayout(self.joystickLayout)
            self.verticalLayout.setObjectName("verticalLayout")
            self.jsXAxisLayout = QtWidgets.QHBoxLayout()
            self.jsXAxisLayout.setObjectName("jsXAxisLayout")
            self.jsXAxisLabel = QtWidgets.QLabel(self.joystickLayout)
            self.jsXAxisLabel.setObjectName("jsXAxisLabel")
            self.jsXAxisLayout.addWidget(self.jsXAxisLabel)
            self.jsXAxisLayout_2 = QtWidgets.QVBoxLayout()
            self.jsXAxisLayout_2.setSpacing(0)
            self.jsXAxisLayout_2.setObjectName("jsXAxisLayout_2")
            self.jsXAxisComboBox = QtWidgets.QComboBox(self.joystickLayout)
            self.jsXAxisComboBox.setObjectName("jsXAxisComboBox")
            self.jsXAxisComboBox.addItem("")
            self.jsXAxisComboBox.addItem("")
            self.jsXAxisComboBox.addItem("")
            self.jsXAxisLayout_2.addWidget(self.jsXAxisComboBox)
            self.jsXLeftWidget = QtWidgets.QWidget(self.joystickLayout)
            self.jsXLeftWidget.setEnabled(False)
            self.jsXLeftWidget.setObjectName("jsXLeftWidget")
            self.gridLayout_3 = QtWidgets.QGridLayout(self.jsXLeftWidget)
            self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
            self.gridLayout_3.setSpacing(0)
            self.gridLayout_3.setObjectName("gridLayout_3")
            self.jsXLeftLabel = QtWidgets.QLabel(self.jsXLeftWidget)
            self.jsXLeftLabel.setObjectName("jsXLeftLabel")
            self.gridLayout_3.addWidget(self.jsXLeftLabel, 0, 0, 1, 1)
            self.jsXLeftLabelSpinBox = QtWidgets.QSpinBox(self.jsXLeftWidget)
            self.jsXLeftLabelSpinBox.setMaximum(127)
            self.jsXLeftLabelSpinBox.setObjectName("jsXLeftLabelSpinBox")
            self.gridLayout_3.addWidget(self.jsXLeftLabelSpinBox, 0, 1, 1, 1)
            self.jsXRightLabel = QtWidgets.QLabel(self.jsXLeftWidget)
            self.jsXRightLabel.setObjectName("jsXRightLabel")
            self.gridLayout_3.addWidget(self.jsXRightLabel, 1, 0, 1, 1)
            self.jsXRightSpinBox = QtWidgets.QSpinBox(self.jsXLeftWidget)
            self.jsXRightSpinBox.setMaximum(127)
            self.jsXRightSpinBox.setObjectName("jsXRightSpinBox")
            self.gridLayout_3.addWidget(self.jsXRightSpinBox, 1, 1, 1, 1)
            self.jsXLeftLabelSpinBox.raise_()
            self.jsXRightSpinBox.raise_()
            self.jsXLeftLabel.raise_()
            self.jsXRightLabel.raise_()
            self.jsXAxisLayout_2.addWidget(self.jsXLeftWidget)
            self.jsXAxisLayout.addLayout(self.jsXAxisLayout_2)
            self.verticalLayout.addLayout(self.jsXAxisLayout)
            self.jsYAxisLayout = QtWidgets.QHBoxLayout()
            self.jsYAxisLayout.setObjectName("jsYAxisLayout")
            self.jsYAxisLabel = QtWidgets.QLabel(self.joystickLayout)
            self.jsYAxisLabel.setObjectName("jsYAxisLabel")
            self.jsYAxisLayout.addWidget(self.jsYAxisLabel)
            self.jsYAxisLayout_2 = QtWidgets.QVBoxLayout()
            self.jsYAxisLayout_2.setSpacing(0)
            self.jsYAxisLayout_2.setObjectName("jsYAxisLayout_2")
            self.jsYAxisComboBox = QtWidgets.QComboBox(self.joystickLayout)
            self.jsYAxisComboBox.setObjectName("jsYAxisComboBox")
            self.jsYAxisComboBox.addItem("")
            self.jsYAxisComboBox.addItem("")
            self.jsYAxisComboBox.addItem("")
            self.jsYAxisLayout_2.addWidget(self.jsYAxisComboBox)
            self.jsYWidget = QtWidgets.QWidget(self.joystickLayout)
            self.jsYWidget.setEnabled(False)
            self.jsYWidget.setObjectName("jsYWidget")
            self.gridLayout_7 = QtWidgets.QGridLayout(self.jsYWidget)
            self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
            self.gridLayout_7.setSpacing(0)
            self.gridLayout_7.setObjectName("gridLayout_7")
            self.jsYUpLabel = QtWidgets.QLabel(self.jsYWidget)
            self.jsYUpLabel.setObjectName("jsYUpLabel")
            self.gridLayout_7.addWidget(self.jsYUpLabel, 0, 0, 1, 1)
            self.jsYUpSpinBox = QtWidgets.QSpinBox(self.jsYWidget)
            self.jsYUpSpinBox.setMaximum(127)
            self.jsYUpSpinBox.setObjectName("jsYUpSpinBox")
            self.gridLayout_7.addWidget(self.jsYUpSpinBox, 0, 1, 1, 1)
            self.jsYDownLabel = QtWidgets.QLabel(self.jsYWidget)
            self.jsYDownLabel.setObjectName("jsYDownLabel")
            self.gridLayout_7.addWidget(self.jsYDownLabel, 1, 0, 1, 1)
            self.jsYDownSpinBox = QtWidgets.QSpinBox(self.jsYWidget)
            self.jsYDownSpinBox.setMaximum(127)
            self.jsYDownSpinBox.setObjectName("jsYDownSpinBox")
            self.gridLayout_7.addWidget(self.jsYDownSpinBox, 1, 1, 1, 1)
            self.jsYAxisLayout_2.addWidget(self.jsYWidget)
            self.jsYAxisLayout.addLayout(self.jsYAxisLayout_2)
            self.verticalLayout.addLayout(self.jsYAxisLayout)
            self.miscLayout.addWidget(self.joystickLayout)
            self.arpegGroupBox = QtWidgets.QGroupBox(prog["prog1"])
            self.arpegGroupBox.setObjectName("arpegGroupBox")
            self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.arpegGroupBox)
            self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
            self.verticalLayout_3.setSpacing(0)
            self.verticalLayout_3.setObjectName("verticalLayout_3")
            self.tempoLayout = QtWidgets.QHBoxLayout()
            self.tempoLayout.setObjectName("tempoLayout")
            self.tempoLabel = QtWidgets.QLabel(self.arpegGroupBox)
            self.tempoLabel.setObjectName("tempoLabel")
            self.tempoLayout.addWidget(self.tempoLabel)
            self.tempoSpinBox = QtWidgets.QSpinBox(self.arpegGroupBox)
            self.tempoSpinBox.setMinimum(30)
            self.tempoSpinBox.setMaximum(240)
            self.tempoSpinBox.setProperty("value", 120)
            self.tempoSpinBox.setObjectName("tempoSpinBox")
            self.tempoLayout.addWidget(self.tempoSpinBox)
            self.verticalLayout_3.addLayout(self.tempoLayout)
            self.timeDivLayout = QtWidgets.QHBoxLayout()
            self.timeDivLayout.setObjectName("timeDivLayout")
            self.timeDivLabel = QtWidgets.QLabel(self.arpegGroupBox)
            self.timeDivLabel.setObjectName("timeDivLabel")
            self.timeDivLayout.addWidget(self.timeDivLabel)
            self.timeDivComboBox = QtWidgets.QComboBox(self.arpegGroupBox)
            self.timeDivComboBox.setObjectName("timeDivComboBox")
            self.timeDivComboBox.addItem("")
            self.timeDivComboBox.addItem("")
            self.timeDivComboBox.addItem("")
            self.timeDivComboBox.addItem("")
            self.timeDivComboBox.addItem("")
            self.timeDivComboBox.addItem("")
            self.timeDivComboBox.addItem("")
            self.timeDivComboBox.addItem("")
            self.timeDivLayout.addWidget(self.timeDivComboBox)
            self.verticalLayout_3.addLayout(self.timeDivLayout)
            self.swingLayout = QtWidgets.QHBoxLayout()
            self.swingLayout.setObjectName("swingLayout")
            self.swingLabel = QtWidgets.QLabel(self.arpegGroupBox)
            self.swingLabel.setObjectName("swingLabel")
            self.swingLayout.addWidget(self.swingLabel)
            self.swingComboBox = QtWidgets.QComboBox(self.arpegGroupBox)
            self.swingComboBox.setObjectName("swingComboBox")
            self.swingComboBox.addItem("")
            self.swingComboBox.addItem("")
            self.swingComboBox.addItem("")
            self.swingComboBox.addItem("")
            self.swingComboBox.addItem("")
            self.swingComboBox.addItem("")
            self.swingLayout.addWidget(self.swingComboBox)
            self.verticalLayout_3.addLayout(self.swingLayout)
            self.arpOctaveLayout = QtWidgets.QHBoxLayout()
            self.arpOctaveLayout.setObjectName("arpOctaveLayout")
            self.arpOctaveLabel = QtWidgets.QLabel(self.arpegGroupBox)
            self.arpOctaveLabel.setObjectName("arpOctaveLabel")
            self.arpOctaveLayout.addWidget(self.arpOctaveLabel)
            self.arpOctaveSpinBox = QtWidgets.QSpinBox(self.arpegGroupBox)
            self.arpOctaveSpinBox.setMinimum(0)
            self.arpOctaveSpinBox.setMaximum(4)
            self.arpOctaveSpinBox.setProperty("value", 0)
            self.arpOctaveSpinBox.setObjectName("arpOctaveSpinBox")
            self.arpOctaveLayout.addWidget(self.arpOctaveSpinBox)
            self.verticalLayout_3.addLayout(self.arpOctaveLayout)
            self.modeLayout = QtWidgets.QHBoxLayout()
            self.modeLayout.setObjectName("modeLayout")
            self.modeLabel = QtWidgets.QLabel(self.arpegGroupBox)
            self.modeLabel.setObjectName("modeLabel")
            self.modeLayout.addWidget(self.modeLabel)
            self.modeComboBox = QtWidgets.QComboBox(self.arpegGroupBox)
            self.modeComboBox.setObjectName("modeComboBox")
            self.modeComboBox.addItem("")
            self.modeComboBox.addItem("")
            self.modeComboBox.addItem("")
            self.modeComboBox.addItem("")
            self.modeComboBox.addItem("")
            self.modeComboBox.addItem("")
            self.modeLayout.addWidget(self.modeComboBox)
            self.verticalLayout_3.addLayout(self.modeLayout)
            self.tempoTapsLayout = QtWidgets.QHBoxLayout()
            self.tempoTapsLayout.setObjectName("tempoTapsLayout")
            self.tempoTapsLabel = QtWidgets.QLabel(self.arpegGroupBox)
            self.tempoTapsLabel.setObjectName("tempoTapsLabel")
            self.tempoTapsLayout.addWidget(self.tempoTapsLabel)
            self.tempoTapsSpinBox = QtWidgets.QSpinBox(self.arpegGroupBox)
            self.tempoTapsSpinBox.setMinimum(2)
            self.tempoTapsSpinBox.setMaximum(4)
            self.tempoTapsSpinBox.setProperty("value", 2)
            self.tempoTapsSpinBox.setObjectName("tempoTapsSpinBox")
            self.tempoTapsLayout.addWidget(self.tempoTapsSpinBox)
            self.verticalLayout_3.addLayout(self.tempoTapsLayout)
            self.clockLayout = QtWidgets.QHBoxLayout()
            self.clockLayout.setObjectName("clockLayout")
            self.clockLabel = QtWidgets.QLabel(self.arpegGroupBox)
            self.clockLabel.setObjectName("clockLabel")
            self.clockLayout.addWidget(self.clockLabel)
            self.clockComboBox = QtWidgets.QComboBox(self.arpegGroupBox)
            self.clockComboBox.setObjectName("clockComboBox")
            self.clockComboBox.addItem("")
            self.clockComboBox.addItem("")
            self.clockLayout.addWidget(self.clockComboBox)
            self.verticalLayout_3.addLayout(self.clockLayout)
            self.arpCheckBox = QtWidgets.QCheckBox(self.arpegGroupBox)
            self.arpCheckBox.setObjectName("arpCheckBox")
            self.verticalLayout_3.addWidget(self.arpCheckBox)
            self.miscLayout.addWidget(self.arpegGroupBox)
            self.chanKeysLayout = QtWidgets.QVBoxLayout()
            self.chanKeysLayout.setObjectName("chanKeysLayout")
            self.channelsGroupBox = QtWidgets.QGroupBox(prog["prog1"])
            self.channelsGroupBox.setObjectName("channelsGroupBox")
            self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.channelsGroupBox)
            self.verticalLayout_5.setObjectName("verticalLayout_5")
            self.padLayout = QtWidgets.QHBoxLayout()
            self.padLayout.setObjectName("padLayout")
            self.padLabel = QtWidgets.QLabel(self.channelsGroupBox)
            self.padLabel.setObjectName("padLabel")
            self.padLayout.addWidget(self.padLabel)
            self.padSpinBox = QtWidgets.QSpinBox(self.channelsGroupBox)
            self.padSpinBox.setMinimum(1)
            self.padSpinBox.setMaximum(16)
            self.padSpinBox.setObjectName("padSpinBox")
            self.padLayout.addWidget(self.padSpinBox)
            self.verticalLayout_5.addLayout(self.padLayout)
            self.keysLayout = QtWidgets.QHBoxLayout()
            self.keysLayout.setObjectName("keysLayout")
            self.keysLabel = QtWidgets.QLabel(self.channelsGroupBox)
            self.keysLabel.setObjectName("keysLabel")
            self.keysLayout.addWidget(self.keysLabel)
            self.keySpinBox = QtWidgets.QSpinBox(self.channelsGroupBox)
            self.keySpinBox.setMinimum(1)
            self.keySpinBox.setMaximum(16)
            self.keySpinBox.setObjectName("keySpinBox")
            self.keysLayout.addWidget(self.keySpinBox)
            self.verticalLayout_5.addLayout(self.keysLayout)
            self.chanKeysLayout.addWidget(self.channelsGroupBox)
            self.keyboardGroupBox = QtWidgets.QGroupBox(prog["prog1"])
            self.keyboardGroupBox.setObjectName("keyboardGroupBox")
            self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.keyboardGroupBox)
            self.verticalLayout_4.setObjectName("verticalLayout_4")
            self.transposeLayout = QtWidgets.QHBoxLayout()
            self.transposeLayout.setObjectName("transposeLayout")
            self.transposeLabel = QtWidgets.QLabel(self.keyboardGroupBox)
            self.transposeLabel.setObjectName("transposeLabel")
            self.transposeLayout.addWidget(self.transposeLabel)
            self.transposeSpinBox = QtWidgets.QSpinBox(self.keyboardGroupBox)
            self.transposeSpinBox.setMinimum(-12)
            self.transposeSpinBox.setMaximum(12)
            self.transposeSpinBox.setObjectName("transposeSpinBox")
            self.transposeLayout.addWidget(self.transposeSpinBox)
            self.verticalLayout_4.addLayout(self.transposeLayout)
            self.octaveLayout = QtWidgets.QHBoxLayout()
            self.octaveLayout.setObjectName("octaveLayout")
            self.octaveLabel = QtWidgets.QLabel(self.keyboardGroupBox)
            self.octaveLabel.setObjectName("octaveLabel")
            self.octaveLayout.addWidget(self.octaveLabel)
            self.octaveSpinBox = QtWidgets.QSpinBox(self.keyboardGroupBox)
            self.octaveSpinBox.setMinimum(-4)
            self.octaveSpinBox.setMaximum(4)
            self.octaveSpinBox.setObjectName("octaveSpinBox")
            self.octaveLayout.addWidget(self.octaveSpinBox)
            self.verticalLayout_4.addLayout(self.octaveLayout)
            self.chanKeysLayout.addWidget(self.keyboardGroupBox)
            self.miscLayout.addLayout(self.chanKeysLayout)
            self.gridLayout_2.addLayout(self.miscLayout, 2, 1, 1, 1)
            self.bankAGroupBox = QtWidgets.QGroupBox(prog["prog1"])
            self.bankAGroupBox.setObjectName("bankAGroupBox")
            self.gridLayout_6 = QtWidgets.QGridLayout(self.bankAGroupBox)
            self.gridLayout_6.setContentsMargins(2, 2, 2, 2)
            self.gridLayout_6.setSpacing(2)
            self.gridLayout_6.setObjectName("gridLayout_6")
            self.pad1GroupBox = QtWidgets.QGroupBox(self.bankAGroupBox)
            self.pad1GroupBox.setObjectName("pad1GroupBox")
            self.gridLayout_43 = QtWidgets.QGridLayout(self.pad1GroupBox)
            self.gridLayout_43.setContentsMargins(0, 0, 0, 0)
            self.gridLayout_43.setSpacing(0)
            self.gridLayout_43.setObjectName("gridLayout_43")
            self.pad1CCLayout = QtWidgets.QHBoxLayout()
            self.pad1CCLayout.setObjectName("pad1CCLayout")
            self.pad1CCLabel = QtWidgets.QLabel(self.pad1GroupBox)
            self.pad1CCLabel.setObjectName("pad1CCLabel")
            self.pad1CCLayout.addWidget(self.pad1CCLabel)
            self.pad1CCSpinBox = QtWidgets.QSpinBox(self.pad1GroupBox)
            self.pad1CCSpinBox.setMaximum(127)
            self.pad1CCSpinBox.setProperty("value", 0)
            self.pad1CCSpinBox.setObjectName("pad1CCSpinBox")
            self.pad1CCLayout.addWidget(self.pad1CCSpinBox)
            self.gridLayout_43.addLayout(self.pad1CCLayout, 2, 0, 1, 1)
            self.pad1TypeComboBox = QtWidgets.QComboBox(self.pad1GroupBox)
            self.pad1TypeComboBox.setObjectName("pad1TypeComboBox")
            self.pad1TypeComboBox.addItem("")
            self.pad1TypeComboBox.addItem("")
            self.gridLayout_43.addWidget(self.pad1TypeComboBox, 4, 0, 1, 1)
            self.pad1NoteLayout = QtWidgets.QHBoxLayout()
            self.pad1NoteLayout.setObjectName("pad1NoteLayout")
            self.pad1NoteLabel = QtWidgets.QLabel(self.pad1GroupBox)
            self.pad1NoteLabel.setObjectName("pad1NoteLabel")
            self.pad1NoteLayout.addWidget(self.pad1NoteLabel)
            self.pad1NoteSpinBox = QtWidgets.QSpinBox(self.pad1GroupBox)
            self.pad1NoteSpinBox.setMinimum(-1)
            self.pad1NoteSpinBox.setMaximum(9)
            self.pad1NoteSpinBox.setProperty("value", 4)
            self.pad1NoteSpinBox.setObjectName("pad1NoteSpinBox")
            self.pad1NoteLayout.addWidget(self.pad1NoteSpinBox)
            self.pad1NoteComboBox = QtWidgets.QComboBox(self.pad1GroupBox)
            self.pad1NoteComboBox.setObjectName("pad1NoteComboBox")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteComboBox.addItem("")
            self.pad1NoteLayout.addWidget(self.pad1NoteComboBox)
            self.gridLayout_43.addLayout(self.pad1NoteLayout, 0, 0, 1, 1)
            self.pad1MIDILayout = QtWidgets.QHBoxLayout()
            self.pad1MIDILayout.setObjectName("pad1MIDILayout")
            self.pad1MIDILabel = QtWidgets.QLabel(self.pad1GroupBox)
            self.pad1MIDILabel.setObjectName("pad1MIDILabel")
            self.pad1MIDILayout.addWidget(self.pad1MIDILabel)
            self.pad1MIDISpinBox = QtWidgets.QSpinBox(self.pad1GroupBox)
            self.pad1MIDISpinBox.setMaximum(127)
            self.pad1MIDISpinBox.setProperty("value", 0)
            self.pad1MIDISpinBox.setObjectName("pad1MIDISpinBox")
            self.pad1MIDILayout.addWidget(self.pad1MIDISpinBox)
            self.gridLayout_43.addLayout(self.pad1MIDILayout, 1, 0, 1, 1)
            self.pad1PCLayout = QtWidgets.QHBoxLayout()
            self.pad1PCLayout.setObjectName("pad1PCLayout")
            self.pad1PCLabel = QtWidgets.QLabel(self.pad1GroupBox)
            self.pad1PCLabel.setObjectName("pad1PCLabel")
            self.pad1PCLayout.addWidget(self.pad1PCLabel)
            self.pad1PCSpinBox = QtWidgets.QSpinBox(self.pad1GroupBox)
            self.pad1PCSpinBox.setMaximum(127)
            self.pad1PCSpinBox.setProperty("value", 0)
            self.pad1PCSpinBox.setObjectName("pad1PCSpinBox")
            self.pad1PCLayout.addWidget(self.pad1PCSpinBox)
            self.gridLayout_43.addLayout(self.pad1PCLayout, 3, 0, 1, 1)
            self.gridLayout_6.addWidget(self.pad1GroupBox, 3, 0, 1, 1)
            self.gridLayout_2.addWidget(self.bankAGroupBox, 2, 0, 1, 1)
            self.programmes.addTab(prog["prog1"], "")
            self.progs.append(prog)
        self.gridLayout.addWidget(self.programmes, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1032, 18))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuFile_2 = QtWidgets.QMenu(self.menubar)
        self.menuFile_2.setObjectName("menuFile_2")
        MainWindow.setMenuBar(self.menubar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtWidgets.QAction(MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_as_2 = QtWidgets.QAction(MainWindow)
        self.actionSave_as_2.setObjectName("actionSave_as_2")
        self.actionFactory_preset = QtWidgets.QAction(MainWindow)
        self.actionFactory_preset.setObjectName("actionFactory_preset")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as_2)
        self.menuFile.addAction(self.actionFactory_preset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuFile_2.menuAction())

        self.retranslateUi(MainWindow)
        self.programmes.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.getAllPushButton.setText(_translate("MainWindow", "Get all"))
        self.getCurrentPushButton.setText(_translate("MainWindow", "Get current"))
        self.sendCurrentPushButton.setText(_translate("MainWindow", "Send current"))
        self.sendAllPushButton.setText(_translate("MainWindow", "Send all"))
        self.liveUpdateCheckBox.setText(_translate("MainWindow", "Live update"))
        self.knobsGroupBox.setTitle(_translate("MainWindow", "Knobs"))
        for pi, prog in enumerate(self.progs):
            for ki, knob in enumerate(prog["knobs"]):
                knob["knobGroupBox"].setTitle(_translate("MainWindow", "Knob %s" % (ki+1)))
                knob["knobMinLabel"].setText(_translate("MainWindow", "Min"))
                knob["knobMaxLabel"].setText(_translate("MainWindow", "Max"))
                knob["knobCCLabel"].setText(_translate("MainWindow", "CC"))
        self.joystickLayout.setTitle(_translate("MainWindow", "Joystick"))
        self.jsXAxisLabel.setText(_translate("MainWindow", "X Axis"))
        self.jsXAxisComboBox.setItemText(0, _translate("MainWindow", "Pitchbend"))
        self.jsXAxisComboBox.setItemText(1, _translate("MainWindow", "CC 1"))
        self.jsXAxisComboBox.setItemText(2, _translate("MainWindow", "CC 2"))
        self.jsXLeftLabel.setText(_translate("MainWindow", "Left"))
        self.jsXRightLabel.setText(_translate("MainWindow", "Right"))
        self.jsYAxisLabel.setText(_translate("MainWindow", "Y Axis"))
        self.jsYAxisComboBox.setItemText(0, _translate("MainWindow", "Pitchbend"))
        self.jsYAxisComboBox.setItemText(1, _translate("MainWindow", "CC 1"))
        self.jsYAxisComboBox.setItemText(2, _translate("MainWindow", "CC 2"))
        self.jsYUpLabel.setText(_translate("MainWindow", "Up"))
        self.jsYDownLabel.setText(_translate("MainWindow", "Down"))
        self.arpegGroupBox.setTitle(_translate("MainWindow", "Arpeggiator"))
        self.tempoLabel.setText(_translate("MainWindow", "Tempo"))
        self.timeDivLabel.setText(_translate("MainWindow", "Time div"))
        self.timeDivComboBox.setItemText(0, _translate("MainWindow", "1/4"))
        self.timeDivComboBox.setItemText(1, _translate("MainWindow", "1/4T"))
        self.timeDivComboBox.setItemText(2, _translate("MainWindow", "1/8"))
        self.timeDivComboBox.setItemText(3, _translate("MainWindow", "1/8T"))
        self.timeDivComboBox.setItemText(4, _translate("MainWindow", "1/16"))
        self.timeDivComboBox.setItemText(5, _translate("MainWindow", "1/16T"))
        self.timeDivComboBox.setItemText(6, _translate("MainWindow", "1/32"))
        self.timeDivComboBox.setItemText(7, _translate("MainWindow", "1/32T"))
        self.swingLabel.setText(_translate("MainWindow", "Swing"))
        self.swingComboBox.setItemText(0, _translate("MainWindow", "50%"))
        self.swingComboBox.setItemText(1, _translate("MainWindow", "55%"))
        self.swingComboBox.setItemText(2, _translate("MainWindow", "57%"))
        self.swingComboBox.setItemText(3, _translate("MainWindow", "59%"))
        self.swingComboBox.setItemText(4, _translate("MainWindow", "61%"))
        self.swingComboBox.setItemText(5, _translate("MainWindow", "64%"))
        self.arpOctaveLabel.setText(_translate("MainWindow", "Octave"))
        self.modeLabel.setText(_translate("MainWindow", "Mode"))
        self.modeComboBox.setItemText(0, _translate("MainWindow", "UP"))
        self.modeComboBox.setItemText(1, _translate("MainWindow", "DOWN"))
        self.modeComboBox.setItemText(2, _translate("MainWindow", "EXCLUSIVE"))
        self.modeComboBox.setItemText(3, _translate("MainWindow", "INCLUSIVE"))
        self.modeComboBox.setItemText(4, _translate("MainWindow", "ORDER"))
        self.modeComboBox.setItemText(5, _translate("MainWindow", "RANDOM"))
        self.tempoTapsLabel.setText(_translate("MainWindow", "Tempo taps"))
        self.clockLabel.setText(_translate("MainWindow", "Clock"))
        self.clockComboBox.setItemText(0, _translate("MainWindow", "Internal"))
        self.clockComboBox.setItemText(1, _translate("MainWindow", "Eternal"))
        self.arpCheckBox.setToolTip(_translate("MainWindow", "<html><head/><body><p>Activate arpeggiator</p></body></html>"))
        self.arpCheckBox.setText(_translate("MainWindow", "ON/OFF"))
        self.channelsGroupBox.setTitle(_translate("MainWindow", "Channels"))
        self.padLabel.setText(_translate("MainWindow", "Pad"))
        self.keysLabel.setText(_translate("MainWindow", "Keys/CC"))
        self.keyboardGroupBox.setTitle(_translate("MainWindow", "Keyboard"))
        self.transposeLabel.setText(_translate("MainWindow", "Transpose"))
        self.octaveLabel.setText(_translate("MainWindow", "Octave"))
        self.bankAGroupBox.setTitle(_translate("MainWindow", "Bank A"))
        self.pad1GroupBox.setTitle(_translate("MainWindow", "Pad 5"))
        self.pad1CCLabel.setText(_translate("MainWindow", "CC"))
        self.pad1TypeComboBox.setItemText(0, _translate("MainWindow", "Toggle"))
        self.pad1TypeComboBox.setItemText(1, _translate("MainWindow", "Momentary"))
        self.pad1NoteLabel.setText(_translate("MainWindow", "Note"))
        self.pad1NoteComboBox.setItemText(0, _translate("MainWindow", "C"))
        self.pad1NoteComboBox.setItemText(1, _translate("MainWindow", "C#"))
        self.pad1NoteComboBox.setItemText(2, _translate("MainWindow", "D"))
        self.pad1NoteComboBox.setItemText(3, _translate("MainWindow", "D#"))
        self.pad1NoteComboBox.setItemText(4, _translate("MainWindow", "E"))
        self.pad1NoteComboBox.setItemText(5, _translate("MainWindow", "F"))
        self.pad1NoteComboBox.setItemText(6, _translate("MainWindow", "F#"))
        self.pad1NoteComboBox.setItemText(7, _translate("MainWindow", "G"))
        self.pad1NoteComboBox.setItemText(8, _translate("MainWindow", "G#"))
        self.pad1NoteComboBox.setItemText(9, _translate("MainWindow", "A"))
        self.pad1NoteComboBox.setItemText(10, _translate("MainWindow", "B"))
        self.pad1MIDILabel.setText(_translate("MainWindow", "MIDI"))
        self.pad1PCLabel.setText(_translate("MainWindow", "PC"))
        for i, prog in enumerate(self.progs):
            print(prog)
            self.programmes.setTabText(self.programmes.indexOf(prog["prog1"]), _translate("MainWindow", "PROG %s"%(i+1)))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuFile_2.setTitle(_translate("MainWindow", "Edit"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as..."))
        self.actionSave_as_2.setText(_translate("MainWindow", "Save as..."))
        self.actionFactory_preset.setText(_translate("MainWindow", "Factory preset"))
